import { cn } from "@/lib/cn";
import { Watermark } from "@/components/product/Watermark";

/* ============================================================================
   INDUSTRY SCENE PHOTOGRAPH
   ============================================================================
   Illustrative photography for the industries page, generated by
   `npm run images` from the masters in assets-src/industries/.

   These are NOT documentary photographs and NOT product output. They are
   generated scenes that depict the *situation* a sector faces — never the
   product, never a certificate, never the app interface. That line is
   deliberate and load-bearing: PhoneShot exists precisely because illustrating
   an authenticity product with imagery it cannot vouch for undercuts the
   argument the site is making. Real screens come from PhoneShot; the world
   around them comes from here.

   Consequently: if a scene ever needs to show a phone screen, the screen shows
   a plain camera view, not a Delphi Verify interface.
   ========================================================================= */

/* Intrinsic aspect ratio of the source masters (2720×1530 — true 16:9).
   Declared so the browser reserves space and the page does not shift as
   images load; eight of these on one page would otherwise thrash the layout. */
const RATIO_W = 2720;
const RATIO_H = 1530;

export function IndustryShot({
  name,
  alt,
  className,
}: {
  /** Basename in public/assets/industries, e.g. "property-sales". */
  name: string;
  /** Describe the scene, not "photo of an industry". */
  alt: string;
  className?: string;
}) {
  const base = `/assets/industries/${name}`;

  return (
    <div className="relative h-full w-full">
      <img
        src={`${base}-1120.webp`}
        srcSet={`${base}-560.webp 560w, ${base}-1120.webp 1120w`}
        sizes="(min-width: 1024px) 500px, (min-width: 640px) 600px, 92vw"
        width={RATIO_W}
        height={RATIO_H}
        alt={alt}
        /* Never eager. Every one of these sits well below the fold — the page
         opens on the hero and the qualifying test. */
        loading="lazy"
        decoding="async"
        className={cn(
          "block h-full w-full rounded-md border border-line object-cover",
          className,
        )}
      />
      <Watermark />
    </div>
  );
}
