import { cn } from "@/lib/cn";

/* ============================================================================
   PRODUCT SCREENSHOT
   ============================================================================
   Real captures from the Delphi Verify iOS app, generated by
   `npm run images` from the masters in the shared Assets folder.

   The device frame and drop shadow are baked into the source PNG, so nothing
   is drawn around them here — adding a CSS bezel would double it up.

   Using the product's own output rather than stock photography is a deliberate
   choice: illustrating an authenticity product with licensed stock imagery
   undercuts the argument it is making.
   ========================================================================= */

export type ShotName =
  | "capture"
  | "certificate"
  | "certificate-location"
  | "scan"
  | "packs";

/* Intrinsic aspect ratio of the source masters (1350×2760). Declared so the
   browser reserves space and the page does not shift as images load. */
const RATIO_W = 1350;
const RATIO_H = 2760;

export function PhoneShot({
  name,
  alt,
  className,
  priority = false,
}: {
  name: ShotName;
  /** Describe what the screen shows, not "screenshot of app". */
  alt: string;
  className?: string;
  /** Set on the single most important image above the fold. */
  priority?: boolean;
}) {
  const base = `/assets/product/${name}`;

  return (
    <img
      src={`${base}-680.webp`}
      srcSet={`${base}-340.webp 340w, ${base}-680.webp 680w`}
      sizes="(min-width: 1024px) 340px, (min-width: 640px) 300px, 260px"
      width={RATIO_W}
      height={RATIO_H}
      alt={alt}
      loading={priority ? "eager" : "lazy"}
      fetchPriority={priority ? "high" : "auto"}
      decoding="async"
      className={cn("block h-auto w-full max-w-[340px]", className)}
    />
  );
}

/** Several shots in a row, staggered so they read as one product rather than
 *  three unrelated images. Falls back to a single column on small screens. */
export function PhoneShotRow({
  shots,
  className,
}: {
  shots: { name: ShotName; alt: string; caption: string }[];
  className?: string;
}) {
  return (
    <ul
      className={cn(
        "grid gap-10 sm:grid-cols-2 lg:grid-cols-3 lg:gap-8",
        className,
      )}
    >
      {shots.map((shot, i) => (
        <li
          key={shot.name}
          className={cn(
            "flex flex-col items-center gap-6 text-center",
            /* Gentle vertical stagger on wide screens. */
            i === 1 && "lg:mt-10",
            i === 2 && "lg:mt-20",
          )}
        >
          <PhoneShot name={shot.name} alt={shot.alt} />
          <p className="max-w-[34ch] text-body-sm text-ink-secondary">
            {shot.caption}
          </p>
        </li>
      ))}
    </ul>
  );
}
