#!/usr/bin/env node
/* ============================================================================
   PRERENDER
   ============================================================================
   Renders every route to static HTML, so crawlers and social scrapers receive
   real content rather than an empty root div — matching what the previous site
   did, and what a marketing site needs.

   Also emits per-route <title>, description, canonical and Open Graph tags,
   plus robots.txt and sitemap.xml.

   Runs after `vite build` and `vite build --ssr`. See package.json.
   ========================================================================= */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { pathToFileURL } from "node:url";

const ROOT = process.cwd();
const DIST = join(ROOT, "dist");
const SSR = join(ROOT, "dist-ssr", "entry-server.js");

if (!existsSync(SSR)) {
  console.error(`✗ SSR bundle not found at ${SSR}. Run the ssr build first.`);
  process.exit(1);
}

/* Everything comes from the one SSR bundle: the renderer, the eagerly loaded
   page components, and the route metadata. */
const { render, loadRoutes, routeTable: routeMeta, SITE_ORIGIN } = await import(
  pathToFileURL(SSR).href
);

const template = readFileSync(join(DIST, "index.html"), "utf8");
const loaded = await loadRoutes();

const escape = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

function headFor(route) {
  const url = `${SITE_ORIGIN}${route.path}`;
  const title = escape(route.seo.title);
  const desc = escape(route.seo.description);
  /* Generated by `npm run og`. Without it every share — LinkedIn, Slack,
     Teams, WhatsApp — renders as a bare text card. Absolute URL is required:
     scrapers do not resolve relative paths. */
  const ogImage = `${SITE_ORIGIN}/assets/social/og-default.png`;
  const robots =
    route.indexable === false ? '\n    <meta name="robots" content="noindex" />' : "";

  return `
    <title>${title}</title>
    <meta name="description" content="${desc}" />
    <link rel="canonical" href="${url}" />
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Delphi Verify" />
    <meta property="og:title" content="${title}" />
    <meta property="og:description" content="${desc}" />
    <meta property="og:url" content="${url}" />
    <meta property="og:image" content="${ogImage}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:alt" content="Delphi Verify — trusted evidence for the physical world" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${title}" />
    <meta name="twitter:description" content="${desc}" />
    <meta name="twitter:image" content="${ogImage}" />${robots}`;
}

let count = 0;

for (const route of routeMeta) {
  const html = render(route.path, loaded);

  const page = template
    /* Replace the placeholder head block emitted by index.html. */
    .replace(/<title>[\s\S]*?<\/title>/, "")
    .replace(/<meta name="description"[^>]*>/, "")
    .replace(/<meta property="og:[^>]*>/g, "")
    .replace(/<meta name="twitter:[^>]*>/g, "")
    .replace("</head>", `${headFor(route)}\n  </head>`)
    .replace('<div id="root"></div>', `<div id="root">${html}</div>`);

  /* "/" → dist/index.html ; "/platform" → dist/platform/index.html
     Directory form means the served URL keeps its trailing slash and the
     canonical tag matches what is actually served — the mismatch the old
     site had between /product and /product/. */
  const outPath =
    route.path === "/"
      ? join(DIST, "index.html")
      : join(DIST, route.path.replace(/^\//, ""), "index.html");

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, page);
  count++;
  console.log(`  ✓ ${route.path.padEnd(14)} → ${outPath.replace(ROOT, ".")}`);
}

/* ── robots.txt ────────────────────────────────────────────────────────── */
const disallowed = routeMeta.filter((r) => r.indexable === false).map((r) => r.path);

writeFileSync(
  join(DIST, "robots.txt"),
  `User-agent: *
Allow: /

# Auth-gated and API routes expose no indexable public content.
Disallow: /login
Disallow: /signup
Disallow: /verify-email
Disallow: /api/
${disallowed.map((p) => `Disallow: ${p}`).join("\n")}

Sitemap: ${SITE_ORIGIN}/sitemap.xml
`,
);

/* ── sitemap.xml ───────────────────────────────────────────────────────────
   Lists the URLs actually served. The previous sitemap listed non-trailing-
   slash paths that all 301'd, which wastes crawl budget. */
const today = process.env.BUILD_DATE ?? new Date().toISOString().slice(0, 10);

const urls = routeMeta
  .filter((r) => r.indexable !== false)
  .map(
    (r) => `  <url>
    <loc>${SITE_ORIGIN}${r.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${r.changefreq ?? "monthly"}</changefreq>
    <priority>${(r.priority ?? 0.5).toFixed(1)}</priority>
  </url>`,
  )
  .join("\n");

writeFileSync(
  join(DIST, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`,
);

console.log(`\n✓ Prerendered ${count} routes, wrote robots.txt and sitemap.xml`);
